Title: Cuauhtli Hernández Díaz
logo: assets/img/me_11zon.jpg
show_downloads: false
description: Hello there! Te doy la bienvenida a mi portafolio de proyectos de Científico de Datos.
theme: jekyll-theme-dinky
